version: 2.1
orbs:
  node: circleci/node@3.0.0
workflows:
  build:
    jobs:
      - build

jobs:
  build:
    docker:
      - image: circleci/node:14-browsers-legacy
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn install --immutable
      - run:
          name: Unit Test
          command: yarn test
