name: Plugin test & build
on:
  workflow_call:
jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16.16.0
      - name: Validate environment
        run: |
          node --version
          npm --version
      - name: Checkout
        uses: actions/checkout@v3
      - name: Spell Check
        run: |
          npx --yes cspell@6.13.3 -c cspell.config.json "**/*.{ts,tsx,js,go,md,mdx,yml,yaml,json,scss,css}"
  test-and-build-frontend:
    runs-on: ubuntu-20.04
    needs: lint
    steps:
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16.16.0
      - name: Validate environment
        run: |
          node --version
          npm --version
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install frontend dependencies
        run: |
          yarn install --frozen-lockfile;
      - name: Test frontend
        run: |
          if [ -f "./.config/webpack/webpack.config.ts" ]; then
            ./node_modules/.bin/jest --passWithNoTests --maxWorkers 4
          else
            echo "deferring tests to build step"
          fi
      - name: Build frontend
        run: |
          if [ -f "./.config/webpack/webpack.config.ts" ]; then
            if [ -f "./webpack.config.ts" ]; then
              ./node_modules/.bin/webpack -c ./webpack.config.ts --env production
            else
              ./node_modules/.bin/webpack -c ./.config/webpack/webpack.config.ts --env production
            fi
          else
            ./node_modules/.bin/grafana-toolkit plugin:ci-build
          fi
      - name: Build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts-frontend
          path: dist/*
  test-and-build-backend:
    runs-on: ubuntu-20.04
    needs: lint
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19.5
      - name: Install Mage
        run: |
          go install github.com/magefile/mage@latest
      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.51.1
      - name: Validate environment
        run: |
          go version
          mage --version
          golangci-lint --version
      - name: Checkout
        uses: actions/checkout@v3
      - name: Lint backend
        run: |
          mage -v lint
      - name: Test backend
        run: |
          go test -v ./...
      - name: Build backend
        run: |
          mage -v build:linux
      - name: Build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts-backend
          path: dist/*
