name: publish-npm

permissions: {}

on:
  push:
    branches:
      - main
      - poc/monorepo

jobs:
  publish:
    name: Publish ${{ matrix.package.name }}
    runs-on: ubuntu-latest
    # Required for this workflow to have permission to publish NPM packages
    environment: release
    permissions:
      contents: read
      # id-token: write required for npm trusted publishing
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        package:
          - name: plugin-ui
            path: packages/plugin-ui
    steps:
      - name: Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          ref: main
          persist-credentials: false

      # limit releases to version changes - https://github.com/EndBug/version-check
      - name: Check version changes
        uses: EndBug/version-check@5102328418c0130d66ca712d755c303e93368ce2 # v2.1.7
        id: version_check
        with:
          diff-search: true
          file-url: ${{ matrix.package.path }}/package.json

      - name: Version update detected
        if: steps.version_check.outputs.changed == 'true'
        run: 'echo "Version change found in ${{ matrix.package.name }}! New version: ${{ steps.version_check.outputs.version }} (${{ steps.version_check.outputs.type }})"'

      - name: Setup .npmrc file for NPM registry
        if: steps.version_check.outputs.changed == 'true'
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
          registry-url: 'https://registry.npmjs.org'

      # npm trusted publishing requires version ^11.5.1
      - name: Install npm version ^11.5.1
        if: steps.version_check.outputs.changed == 'true'
        run: npm install -g npm@^11.5.1

      - name: Install dependencies
        if: steps.version_check.outputs.changed == 'true'
        run: yarn install --immutable

      - name: Build library
        if: steps.version_check.outputs.changed == 'true'
        run: yarn build

      - name: Publish package to NPM
        if: steps.version_check.outputs.changed == 'true'
        working-directory: ${{ matrix.package.path }}
        run: npm publish --access public
